language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build:production
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  only:
    - master