language: 'node_js'
node_js: '8'
cache:
  directories:
    - node_modules
install:
  - travis_retry npm install
script:
  - npm run test
  - npm run build:icons
  - npm run build:production
jobs:
  include:
    - stage: release
      script: echo "Deploying release on GitHub ..."
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release