language: node_js

# Blocklist
branches:
  except:
    - gh-pages # will be deployed to, no need to build it

before_install:
  - npm install -g npm
  - npm --version || echo npm not installed
  - node --version || echo node not installed
  - echo "package version $PACKAGE_VERSION"

stages:
  - build
  - test
  - release
  - deploy

jobs:
  include:
    # Job: Build
    - stage: build
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      script:
        - npm run build
    # Job: Test
    - stage: test
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      script:
        - npm run test

    # Job: Release
    - stage: release
      script: ls
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release